# Generated by Django 2.1 on 2019-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField()),
                ('to_id', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=256)),
                ('c_date', models.DateTimeField()),
            ],
        ),
    ]
