# Generated by Django 2.1 on 2019-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='testDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('cdate', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
