# Generated by Django 2.1 on 2019-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_testdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='flag',
            field=models.IntegerField(choices=[(0, 'send'), (1, 'recv')], default=0),
            preserve_default=False,
        ),
    ]
