# Generated by Django 2.1 on 2019-01-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messages_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='flag',
        ),
    ]
