# Generated by Django 2.1.5 on 2019-01-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_messages_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default=1000000, max_length=64),
        ),
    ]
