# Generated by Django 2.1.5 on 2019-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
