# Generated by Django 2.1.5 on 2019-01-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190121_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(default=100000, to='chat.UserGroup'),
        ),
    ]
